---
title: "Four Parameters: Categorical"
author: "Aditya Narayan"
format: html
execute: 
  echo: false
---

```{r}
#| label: setup
#| echo: false
#| message: false
library(primer.data)
library(tidyverse)
library(brms)
library(tidybayes)
```

```{r}
#| label: table
tbl_regression(fit_nes)
```

```{r}
#| label: cleaning
#| echo: false
#| message: false
nes_92 <- nes |> 
  filter(year == 1992) |>
  select(pres_vote, sex) |>
  drop_na() |> 
  mutate(pres_vote = case_when(
    pres_vote == "Democrat" ~ "Clinton",
    pres_vote == "Republican" ~ "Bush",
    pres_vote == "Third Party" ~ "Perot"
  ))
```

```{r}
#| label: plot
tibble(sex = c("Female", "Male"))
fit_nes |>
  add_epred_draws(newdata = ndata) |>
    select(sex, .category, .epred) |>
    ggplot(aes(x = .epred, fill = sex)) +
    geom_histogram(bins = 100) +
    facet_grid(~ .category) +
    scale_x_continuous(breaks = c(0.05, 0.3, 0.6), labels = scales::percent_format()) +
    labs(title = "Posterior for Expected Probability of Canadite Support Among Women",
    subtitle = "Women are most likely to support clinton",
    x = "Posterior Probability of Expected Vote Probability",
    y = "Count",
    fill = "Sex")
```

```{r}
 # Output LaTeX equations
cat("
**Clinton's Probability**: 
$$
\\rho_{clinton} = \\frac{e^{\\beta_{0, clinton} + \\beta_{1, clinton} \\text{male}}}{1 + e^{\\beta_{0, clinton} + \\beta_{1, clinton} \\text{male}}}
$$

**Perot's Probability**:
$$
\\rho_{perot} = \\frac{e^{\\beta_{0, perot} + \\beta_{1, perot} \\text{male}}}{1 + e^{\\beta_{0, perot} + \\beta_{1, perot} \\text{male}}}
$$

**Bush's Probability**:
$$
\\rho_{bush} = 1 - \\rho_{clinton} - \\rho_{perot}
$$
")
```

```{r}
#| label: model
#| cache: TRUE
fit_nes <- brm(formula = pres_vote ~ sex, data = nes_92, family = categorical(),
silent = 2, refresh = 0, seed = 76)
```

```{r}
"The NES code we have provides voting data for many decades but we used the data from 1992 to see how gender effects voting results. The question we want to answer is how does Sex affect voting results in 1992. Since the voters can change their opinion when they are voting we do not have 100% certainty that these results are correct, We modeled pres_vote, a character variable, as a multinomial logistic regression model. Women are most likely to support Clinton. About 53% of women claim to support Clinton, although that number could be as high as 58% or as low as 48%."
```
